### ISSUE TITLE
Connecting to KWL 500 W R with easyControls 3.0

### ISSUE THREAD

**Issue by yvansandoz** [baradi09/eazyctrl#7]
I am having problem connecting to my Helios Ventilation with eazyctrl.

The access to the unit locally with the IP or with the Helios easyControls Cloud (cloud.easycontrols.net) works perfectly.

From the setting panel, I believe my Modbus setting is correct:
![Screenshot 2022-03-04 at 09 03 19](https://user-images.githubusercontent.com/68730331/156873675-4d93d460-c4aa-42e1-9806-aa8399d3100e.png)

When I try to connect with eazyctrl, I get the following error message (ConnectionRefusedError: [Errno 61] Connection refused):

yvansandoz@macbook-yvan ~ % eazyctrl get 192.168.1.127 temp_outside_air
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/eazyctrl", line 8, in <module>
    sys.exit(run_eazyctrl())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/eazyctrl.py", line 886, in run_eazyctrl
    _eazyctrl_parse_cmd_line_args()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/eazyctrl.py", line 983, in _eazyctrl_parse_cmd_line_args
    args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/eazyctrl.py", line 916, in _eazyctrl_getftr
    varvalue = ctrl.get_feature(args.feature)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/eazyctrl.py", line 844, in get_feature
    return self.get_variable(varname, varlen, getconv)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/eazyctrl.py", line 771, in get_variable
    with EazyCommunicator(self._server, *self._serverargs) as comm:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/eazyctrl.py", line 603, in __init__
    self._socket.connect((server, port))
ConnectionRefusedError: [Errno 61] Connection refused

But ping works.

Where should I start to look to find a solution?

**Comment by baradi09** [comment]
There is a chance, that Modbus over TCP is not supported by your KWL any more.  The setting page you have seem to be for the Modbus protocol over the serial cable (or whatever can be connected to the Helios machine). Could you check the version number of the Helios firmware? Mine is v2.27. I've read somewhere, that the 3.x versions have only the web interface (port 80) available, when accessed via TCP, but not the Modbus one (port 502).

**Comment by yvansandoz** [comment]
It is quite interesting, I have a brand new unit (KWL 500 W R), connected to the easyControls Cloud 3.0, but the software version is 1.0.13.

<img width="873" alt="Screenshot 2022-03-07 at 08 18 02" src="https://user-images.githubusercontent.com/68730331/156986197-fa4018a5-d796-4104-b9ee-fbd23dc1daed.png">

**Comment by yvansandoz** [comment]
@baradi09 correct, I realised that only Modbus RTU is supported (see Modus description D/E/F attached).

Any chance to make it work? Additional hardware needed?

[easyControls 3.0-Modbus_RTU_25483-001_V01_0521.pdf](https://github.com/baradi09/eazyctrl/files/8214047/easyControls.3.0-Modbus_RTU_25483-001_V01_0521.pdf)

**Comment by baradi09** [comment]
I don't think, that it can be made work easily with additional hardware.

Apparently, for some reasons Helios seems to have dropped the Modbus over TCP option. Probably for security reasons, as it allowed for an unauthenticated access without password.

A workaround, which I have seen [in other home automation system plugins for Helios KWL](https://github.com/iobroker-community-adapters/ioBroker.helios/blob/master/main.js), would be to parse the web-pages served by the KWL and read the relevant values from there (and change them via also web-communication if needed). That is feasible and not too complicated, but would be a completely different approach, which basically would not share any code with the current one in eazyctrl. Unfortunately, currently I don't have the capacity to implement it myself. :disappointed: (Also, it would be probably also depend on the version of EasyControls, as if the web-page structure changed, one would have to update the parser accordingly...)

**Comment by EpfigHA** [comment]
Hello all,

I have a HELIOS KWL 360 with the newest firmware. indeed there is no native TCP Mobus present, only serial.
I bought a WaveShare RS485 to ETH converter. After installing it i was able to configure the Helios Integration IP and got the various sensors exposed by the integration. Unfortunatly no data seems to be pulled from the KWL nor any changes on the buttons seem to have an effect on the KWL.
Any help or advice ?

Mathieu
